require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - benchmarks/**/*.rb
    - vendor/bundle/**/*
  DisplayStyleGuide: true # Include styleguide and reference URLs
  ExtraDetails: true # Include cop details
  SuggestExtensions: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

RSpec/NestedGroups:
  Enabled: false
